### ISSUE TITLE
Suspicion of breaking the Wifi ?

### ISSUE THREAD

**Issue by rezzalex** [dnpwwo/Domoticz-Google-Plugin#27]
Hello,

it is here 100% guessing, Suspicion. nothing proved
My 5Gh Wifi can be sometimes completely overwhelmed with catastrophic time respond and bandwith, whereas the 2.4Gz wifi is also impacted, but fare less.
My Main Google plugin "target" is a Lenovo Smart Display connected with the 5 Gzh Wifi...
Is the Plug in can be the cause ? by the discovering the Google "thing" on the network, or sending messages ? broadcasting ?

Thanks for other inputs

regards

**Comment by rezzalex** [comment]
What if the Google Speaker was already streaming web radio before receiving the message from DomoticZ ?

**Comment by jotheman0303** [comment]
Yep, similar issues here. They are intermittent here, but appear similar. I reconfigured the plugin at some point at it totally killed my wifi initially, eventually it crawled back up, but took some time.
Did not think of potentially 5Ghz band only being impacted, it that may be so

**Comment by rezzalex** [comment]
> Yep, similar issues here. They are intermittent here, but appear similar. I reconfigured the plugin at some point at it totally killed my wifi initially, eventually it crawled back up, but took some time.
> Did not think of potentially 5Ghz band only being impacted, it that may be so

@jotheman0303 , did you do something special while reconfiguring ?

**Comment by jotheman0303** [comment]
Not really, I removed the previous "instance" and then recreated it. Part of my wifi-network (router?) went haywire, for example my phone could not connect properly to the wifi network. All my Google devices started to disconnect from wifi (creating their own wifi-network like they do when they get disconnected from the AP) and then gradually started to reconnect again. It seems it takes some time to straighten out, but it does so by itself. I had noticed something similar before, but this time I linked it to the plugin in a very obvious way.
From my point of view it's no drama though, since it takes some time but eventually sorts itself out...
________________________________

**Comment by rezzalex** [comment]
Hello, closing as it happen not really often and my workaround (disconnect my wifi repeater and reboot it) is acceptable
